### ISSUE TITLE
Unable to locate view 'SearchView'

### ISSUE THREAD

**Issue by jjvdgeer** [elastic/elasticsearch-net-example#7]
I'm stuck trying to find out how to use the NuSearch.Web project. Whenever I open localhost:8080 it tells me:

```
Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'SearchView'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/Search/SearchView-en-US,views/Search/SearchView,Search/SearchView-en-US,Search/SearchView,views/SearchView-en-US,views/SearchView,SearchView-en-US,SearchView,Search/Search
Root path: C:\temp\ES\elasticsearch-net-example-2.x-codecomplete\src\NuSearch.Web
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
   at Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

I tried the code-complete version as well (which uses a newer C# than I have available here, so had to make a few changes) but that has the same problem.

Any ideas?

Thanks.

**Comment by russcam** [comment]
@jjvdgeer The view uses Razor View Engine so has a cshtml file extension. Within the locations inspected, the correct view name is looked for (the very last one, `Search/Search`), but the view engine extensions does not contain the extension for Razor views. Make sure you have the `Nancy.Viewengines.Razor` nuget package installed in Nusearch.Web and that all nuget packages have been restored.

**Comment by jjvdgeer** [comment]
I have the Nancy.Viewengines.Razor package installed and it is being put in the bin\Debug directory as well. It is version 1.1.0.0. The problem remains (although I now don't really need the example to work anymore).

**Comment by russcam** [comment]
is this on the 2.x-codecomplete branch? Is the `Search` directory with `Search.cshtml` also copied to bin\Debug?

**Comment by jjvdgeer** [comment]
Well, it was the 2.x branch I checked it on now, but checked to the codecomplete branch as well now, and it is the same there, yes. Search.cshtml is copied to bin\Debug\Search as expected.

**Comment by russcam** [comment]
would you be able to zip up the non-working solution and email it to me to take a look? You can find my email address in git commits

**Comment by jjvdgeer** [comment]
It should be in your mail now.

**Comment by russcam** [comment]
@jjvdgeer Apologies for not replying sooner 😄 

I tried to replicate the issue but couldn't do so. The good news however is that we have [newer branches of the demo that use ASP.NET Core](https://github.com/elastic/elasticsearch-net-example/tree/5.x-netcore) that you might want to check out. I'm closing this issue.
